import { Commodity } from 'src/app/models/commodities/commodity';
export class CDConstants {
    public static commodities: Commodity[] =
        [
            {
                "id": 1,
                "name": "Adzuki bean",
                "main_exchange": "OSE",
                "mic": "XOSE",
                "contract_size": "2400 kg",
                "symbol": "",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 2,
                "name": "Cocoa",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "10 tons",
                "symbol": "CC",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 3,
                "name": "Coffee C",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "37,500 lb",
                "symbol": "KC",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 4,
                "name": "Corn",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "5000 bu",
                "symbol": "C/ZC (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 5,
                "name": "Corn",
                "main_exchange": "EURONEXT",
                "mic": "",
                "contract_size": "50 tons",
                "symbol": "EMA",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 6,
                "name": "Corn",
                "main_exchange": "DCE",
                "mic": "XDCE",
                "contract_size": "10 metric tons",
                "symbol": "c",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 7,
                "name": "Cotton No.2",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "50,000 lb",
                "symbol": "CT",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 8,
                "name": "Frozen Concentrated Orange Juice",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "15,000 lbs",
                "symbol": "FCOJ-A",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 9,
                "name": "Milk",
                "main_exchange": "CME",
                "mic": "XCME",
                "contract_size": "200,000 lbs",
                "symbol": "DC",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 10,
                "name": "No 2. Soybean",
                "main_exchange": "DCE",
                "mic": "XDCE",
                "contract_size": "10 metric tons",
                "symbol": "b",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 11,
                "name": "Oats",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "5000 bu",
                "symbol": "O/ZO (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 12,
                "name": "Rapeseed",
                "main_exchange": "EURONEXT",
                "mic": "",
                "contract_size": "50 tons",
                "symbol": "ECO",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 13,
                "name": "Robusta coffee",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "10,000kg",
                "symbol": "",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 14,
                "name": "Rough Rice",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "2000 cwt",
                "symbol": "ZR",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 15,
                "name": "Soy Meal",
                "main_exchange": "DCE",
                "mic": "XDCE",
                "contract_size": "10 metric tons",
                "symbol": "m",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 16,
                "name": "Soybean Meal",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "100 short tons",
                "symbol": "SM/ZM (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 17,
                "name": "Soybean Oil",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "60,000 lb",
                "symbol": "BO/ZL (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 18,
                "name": "Soybean Oil",
                "main_exchange": "DCE",
                "mic": "XDCE",
                "contract_size": "10 metric tons",
                "symbol": "y",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 19,
                "name": "Soybeans",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "5000 bu",
                "symbol": "S/ZS (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 20,
                "name": "Sugar No.11",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "112,000 lb",
                "symbol": "SB",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 21,
                "name": "Sugar No.14",
                "main_exchange": "ICE",
                "mic": "IEPA",
                "contract_size": "112,000 lb",
                "symbol": "SE",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 22,
                "name": "Wheat",
                "main_exchange": "CBOT",
                "mic": "XCBT",
                "contract_size": "5000 bu",
                "symbol": "W/ZW (Electronic)",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 23,
                "name": "Wheat",
                "main_exchange": "EURONEXT",
                "mic": "",
                "contract_size": "50 tons",
                "symbol": "EBL",
                "currency": "",
                "category": "Agricultural",
                "sub_category": "Grains, food and fiber"
            },
            {
                "id": 24,
                "name": "Lean Hogs",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "40,000 lb (20 tons)",
                "symbol": "HE",
                "currency": "USD ($)",
                "category": "Agricultural",
                "sub_category": "Livestock and meat"
            },
            {
                "id": 25,
                "name": "Live Cattle",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "40,000 lb (20 tons)",
                "symbol": "LE",
                "currency": "USD ($)",
                "category": "Agricultural",
                "sub_category": "Livestock and meat"
            },
            {
                "id": 26,
                "name": "Feeder Cattle",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "50,000 lb (25 tons)",
                "symbol": "GF",
                "currency": "USD ($)",
                "category": "Agricultural",
                "sub_category": "Livestock and meat"
            },
            {
                "id": 27,
                "name": "WTI Crude Oil",
                "main_exchange": "NYMEX, ICE",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "CL (NYMEX), WTI (ICE)",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 28,
                "name": "Brent Crude",
                "main_exchange": "ICE",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "B",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 29,
                "name": "Ethanol",
                "main_exchange": "CBOT",
                "mic": "",
                "contract_size": "29,000 U.S. gal",
                "symbol": "AC (Open Auction) ZE (Electronic)",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 30,
                "name": "Natural gas",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "10,000 million BTU",
                "symbol": "NG",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 31,
                "name": "Natural gas",
                "main_exchange": "ICE",
                "mic": "",
                "contract_size": "1,000 therms",
                "symbol": "NBP",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 32,
                "name": "Heating Oil",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "HO",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 33,
                "name": "Gulf Coast Gasoline",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "LR",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 34,
                "name": "RBOB Gasoline",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "RB",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 35,
                "name": "Propane",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "1000 bbl (42,000 U.S. gal)",
                "symbol": "PN",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 36,
                "name": "Purified Terephthalic Acid (PTA)",
                "main_exchange": "ZCE",
                "mic": "",
                "contract_size": "5 tons",
                "symbol": "TA",
                "currency": "",
                "category": "Energy",
                "sub_category": ""
            },
            {
                "id": 37,
                "name": "Random Length Lumber",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "110,000 nominal board feet",
                "symbol": "LBS",
                "currency": "",
                "category": "Forest products",
                "sub_category": ""
            },
            {
                "id": 38,
                "name": "Hardwood Pulp",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "20 metric tonnes",
                "symbol": "HWP",
                "currency": "",
                "category": "Forest products",
                "sub_category": ""
            },
            {
                "id": 39,
                "name": "Softwood Pulp",
                "main_exchange": "Chicago Mercantile Exchange",
                "mic": "",
                "contract_size": "20 metric tonnes",
                "symbol": "WP",
                "currency": "",
                "category": "Forest products",
                "sub_category": ""
            },
            {
                "id": 40,
                "name": "LME Copper",
                "main_exchange": "London Metal Exchange, New York",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "HG",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 41,
                "name": "Lead",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 42,
                "name": "Zinc",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 43,
                "name": "Tin",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 44,
                "name": "Aluminium",
                "main_exchange": "London Metal Exchange, New York",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 45,
                "name": "Aluminium alloy",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 46,
                "name": "LME Nickel",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 47,
                "name": "Cobalt",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 48,
                "name": "Molybdenum",
                "main_exchange": "London Metal Exchange",
                "mic": "",
                "contract_size": "Metric Ton",
                "symbol": "",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Industrial"
            },
            {
                "id": 49,
                "name": "Gold",
                "main_exchange": "COMEX",
                "mic": "",
                "contract_size": "100 troy ounces",
                "symbol": "GC",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Precious"
            },
            {
                "id": 50,
                "name": "Platinum",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "50 troy ounces",
                "symbol": "PL",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Precious"
            },
            {
                "id": 51,
                "name": "Palladium",
                "main_exchange": "NYMEX",
                "mic": "",
                "contract_size": "100 troy ounces",
                "symbol": "PA",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Precious"
            },
            {
                "id": 52,
                "name": "Silver",
                "main_exchange": "COMEX",
                "mic": "",
                "contract_size": "5,000 troy ounces",
                "symbol": "SI",
                "currency": "USD ($)",
                "category": "Metals",
                "sub_category": "Precious"
            },
            {
                "id": 53,
                "name": "Palm Oil",
                "main_exchange": "Bursa Malaysia",
                "mic": "",
                "contract_size": "1000 kg",
                "symbol": "",
                "currency": "Malaysian Ringgit (RM)",
                "category": "Other",
                "sub_category": ""
            },
            {
                "id": 54,
                "name": "Rubber",
                "main_exchange": "Tokyo Commodity Exchange",
                "mic": "",
                "contract_size": "5000 kg",
                "symbol": "",
                "currency": "US cents (¢)",
                "category": "Other",
                "sub_category": ""
            },
            {
                "id": 55,
                "name": "Wool",
                "main_exchange": "ASX",
                "mic": "",
                "contract_size": "2500 kg",
                "symbol": "",
                "currency": "AUD ($)",
                "category": "Other",
                "sub_category": ""
            },
            {
                "id": 56,
                "name": "Amber",
                "main_exchange": "Saint Petersburg \"Bourse\"",
                "mic": "",
                "contract_size": "1 kg",
                "symbol": "",
                "currency": "Rub (₽)",
                "category": "Other",
                "sub_category": ""
            }
        ]
}